# Generated by Django 5.0.6 on 2024-05-14 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0005_icecream_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecream',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='ice_cream',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ice_cream.icecream'),
            preserve_default=False,
        ),
    ]
